import axios from 'axios';

const FETCH_AI_RESPONSE_START = 'FETCH_AI_RESPONSE_START';
const FETCH_AI_RESPONSE_SUCCESS = 'FETCH_AI_RESPONSE_SUCCESS';
const FETCH_AI_RESPONSE_FAILURE = 'FETCH_AI_RESPONSE_FAILURE';



